"""Fixed sparse OTFS receiver package.

Public model interface:
    y_dd: complex [B, M, N]
    h_dd: optional complex [B, M, N]
    support_mask: optional float/bool [B, M, N]
    token_logits: float [B, vocab_size]
"""

from .ablation import named_receiver_ablation
from .freeze_manifest import (
    FROZEN_BASELINE_ABLATIONS,
    FROZEN_PUBLIC_APIS,
    FROZEN_RECEIVER_CHAIN,
    FROZEN_TX_RX_CONTRACT,
    RECEIVER_FREEZE_VERSION,
)
from .paper_harness import (
    ReceiverComplexityReport,
    ReceiverPaperTrace,
    build_receiver_paper_trace,
    count_receiver_parameters,
    estimate_receiver_ops,
    named_receiver_paper_ablation,
    receiver_paper_summary,
    summarize_receiver_config,
)
from .config import ReceiverConfig
from .data_consistency import (
    DataConsistencyCorrection,
    DataConsistencyOutput,
)
from .dd_ops import (
    SparseDDOperator,
    SparseDDOperatorState,
    dd_circular_convolve_dense_fft,
    dd_circular_convolve_offgrid_sparse,
    dd_circular_convolve_sparse,
    dd_circular_correlation_offgrid_sparse,
    dd_circular_correlation_sparse,
    offgrid_leakage_kernel,
)
from .denoiser import (
    DenoiserOutput,
    ResidualDDDenoiser,
    build_confidence_map,
    build_uncertainty_map,
)
from .equalizer import (
    EqualizerOutput,
    UnfoldedPICProxBlock,
    UnfoldedPICProxEqualizer,
    complex_soft_threshold,
)
from .losses import (
    ReceiverLossOutput,
    ReceiverLossWeights,
    candidate_margin_regularization,
    candidate_recall_metric,
    confidence_nll_regularization,
    contrastive_token_loss,
    dd_data_consistency_loss,
    denoiser_delta_regularization,
    paper_receiver_loss,
    physics_refinement_loss,
    posterior_entropy_regularization,
    reliability_error_alignment_loss,
    token_ce_loss,
    token_confidence_calibration_loss,
    token_cross_entropy,
    token_dd_codeword_loss,
    token_logit_fusion_consistency_loss,
    token_posterior_nll_loss,
    total_receiver_loss,
    weighted_complex_mse,
)
from .model import LearnableOTFSReceiver, ReceiverOutput
from .offgrid_refinement import (
    LocalPatchExtractor,
    OffGridPathRefinement,
    OffGridRefinementNet,
    apply_offgrid_refinement,
    fractional_offset_l2_loss,
    gain_correction_l2_loss,
)
from .pilot_ce import (
    EmbeddedPilotConfig,
    PilotMasks,
    PilotObservation,
    PilotSparseChannelEstimator,
    build_embedded_pilot_masks,
    extract_pilot_observation,
    insert_embedded_pilot,
    validate_pilot_ce_layout,
)
from .position_encoding import build_dd_position_encoding
from .physics_refinement import (
    PhysicsGuidedPathGainRefiner,
    PhysicsRefinementOutput,
)
from .physics_validation import (
    PhysicsValidationReport,
    adjoint_consistency_error,
    complex_nmse,
    gain_refinement_residual_check,
    integer_sparse_operator_reference,
    leakage_kernel_energy_diagnostics,
    pilot_operator_alignment_check,
    validate_integer_operator,
    validate_offgrid_zero_offset,
    validate_receiver_physics,
)
from .reliability import (
    ReliabilityDiagnostics,
    build_reliability_diagnostics,
    build_symbol_reliability_map,
    posterior_confidence_entropy,
    softmax_confidence_and_entropy,
    token_margin,
)
from .sparse_channel import (
    SparseChannelEstimate,
    SparseChannelEstimator,
    SparseRefinementNet,
    ThresholdSparseEstimator,
    TopKSparseEstimator,
    channel_nmse,
    sparsity_l1_loss,
    support_bce_loss,
)
from .token_classifier import (
    EvidenceHeadDiversityLoss,
    TokenClassifierOutput,
    TokenEmbeddingClassifier,
    evidence_head_diversity_loss,
)
from .token_fusion import (
    DetectorClassifierLogitFusion,
    TokenLogitFusionOutput,
    expand_candidate_logits_to_vocab,
)
from .token_prior import (
    TokenCandidateSelection,
    TokenCodewordPrior,
    TokenPosteriorProxOutput,
    TokenPriorProjection,
    select_token_candidates_by_sketch,
    token_codeword_projection,
    token_codeword_posterior_prox,
)

__all__ = [
    "DataConsistencyCorrection",
    "DataConsistencyOutput",
    "LearnableOTFSReceiver",
    "named_receiver_ablation",
    "FROZEN_BASELINE_ABLATIONS",
    "FROZEN_PUBLIC_APIS",
    "FROZEN_RECEIVER_CHAIN",
    "FROZEN_TX_RX_CONTRACT",
    "RECEIVER_FREEZE_VERSION",
    "ReceiverComplexityReport",
    "ReceiverOutput",
    "ReceiverPaperTrace",
    "ReceiverConfig",
    "DenoiserOutput",
    "EmbeddedPilotConfig",
    "LocalPatchExtractor",
    "OffGridPathRefinement",
    "OffGridRefinementNet",
    "ResidualDDDenoiser",
    "EqualizerOutput",
    "PilotMasks",
    "PilotObservation",
    "PilotSparseChannelEstimator",
    "PhysicsGuidedPathGainRefiner",
    "PhysicsRefinementOutput",
    "PhysicsValidationReport",
    "SparseChannelEstimate",
    "adjoint_consistency_error",
    "complex_nmse",
    "gain_refinement_residual_check",
    "integer_sparse_operator_reference",
    "leakage_kernel_energy_diagnostics",
    "pilot_operator_alignment_check",
    "validate_integer_operator",
    "validate_offgrid_zero_offset",
    "validate_receiver_physics",
    "SparseChannelEstimator",
    "SparseRefinementNet",
    "SparseDDOperator",
    "SparseDDOperatorState",
    "ThresholdSparseEstimator",
    "DetectorClassifierLogitFusion",
    "EvidenceHeadDiversityLoss",
    "TokenClassifierOutput",
    "TokenCandidateSelection",
    "TokenLogitFusionOutput",
    "evidence_head_diversity_loss",
    "expand_candidate_logits_to_vocab",
    "TokenCodewordPrior",
    "TokenEmbeddingClassifier",
    "TokenPosteriorProxOutput",
    "TokenPriorProjection",
    "TopKSparseEstimator",
    "select_token_candidates_by_sketch",
    "UnfoldedPICProxBlock",
    "UnfoldedPICProxEqualizer",
    "build_receiver_paper_trace",
    "channel_nmse",
    "count_receiver_parameters",
    "estimate_receiver_ops",
    "named_receiver_paper_ablation",
    "receiver_paper_summary",
    "summarize_receiver_config",
    "apply_offgrid_refinement",
    "complex_soft_threshold",
    "ReliabilityDiagnostics",
    "ReceiverLossOutput",
    "ReceiverLossWeights",
    "build_reliability_diagnostics",
    "candidate_margin_regularization",
    "candidate_recall_metric",
    "confidence_nll_regularization",
    "contrastive_token_loss",
    "dd_data_consistency_loss",
    "denoiser_delta_regularization",
    "paper_receiver_loss",
    "physics_refinement_loss",
    "posterior_confidence_entropy",
    "posterior_entropy_regularization",
    "reliability_error_alignment_loss",
    "softmax_confidence_and_entropy",
    "token_ce_loss",
    "token_confidence_calibration_loss",
    "token_dd_codeword_loss",
    "token_logit_fusion_consistency_loss",
    "token_margin",
    "token_posterior_nll_loss",
    "weighted_complex_mse",
    "build_embedded_pilot_masks",
    "build_confidence_map",
    "build_dd_position_encoding",
    "build_symbol_reliability_map",
    "build_uncertainty_map",
    "dd_circular_convolve_dense_fft",
    "dd_circular_convolve_offgrid_sparse",
    "dd_circular_convolve_sparse",
    "dd_circular_correlation_offgrid_sparse",
    "dd_circular_correlation_sparse",
    "extract_pilot_observation",
    "fractional_offset_l2_loss",
    "gain_correction_l2_loss",
    "insert_embedded_pilot",
    "offgrid_leakage_kernel",
    "validate_pilot_ce_layout",
    "sparsity_l1_loss",
    "support_bce_loss",
    "token_ce_loss",
    "token_codeword_projection",
    "token_codeword_posterior_prox",
    "token_cross_entropy",
    "total_receiver_loss",
]
